services:
  postgres:
    image: postgres:16
    container_name: hw2_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_secret
      POSTGRES_DB: "Marketing-HW2"

    ports:
      - "5433:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/create_staging_tables.sql:/docker-entrypoint-initdb.d/01_create_staging_tables.sql
      - ./sql/create_core_tables.sql:/docker-entrypoint-initdb.d/02_create_core_tables.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d \"Marketing-HW2\""]
      interval: 5s
      timeout: 5s
      retries: 10

  loader:
    build:
      context: .
      dockerfile: scripts/Dockerfile

    container_name: hw2_loader

    environment:
      DB_NAME: "Marketing-HW2"
      DB_USER: postgres
      DB_PASSWORD: my_secret
      DB_HOST: postgres
      DB_PORT: 5432

    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./sql:/app/sql

    depends_on:
      postgres:
        condition: service_healthy

    command: >
      sh -c "
      python /app/scripts/load_csv_to_staging.py &&
      PGPASSWORD=my_secret psql -h postgres -p 5432 -U postgres -d \"Marketing-HW2\" -f /app/sql/transform_staging_to_core.sql &&
      PGPASSWORD=my_secret psql -h postgres -p 5432 -U postgres -d \"Marketing-HW2\" -f /app/sql/quality_checks.sql &&
      python /app/scripts/create_analytics_views.py &&
      echo 'The data warehouse is ready. You can now open the notebook.'
      "

volumes:
  pgdata: