FROM python:3.11

WORKDIR /app

RUN pip install pandas psycopg2-binary 
RUN apt-get update && \
    apt-get install -y postgresql-client && \
    rm -rf /var/lib/apt/lists/*

COPY scripts/ /app/scripts/
COPY data/ /app/data/

CMD ["python", "/app/scripts/load_csv_to_staging.py"]